[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
authors = ["matthew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3"
rand = "0.8"
